// AUTO-GENERATED by scripts/render-gateway.mjs. Do not edit by hand.
const ROUTES = [
  {
    "id": "DM001",
    "mount": "/",
    "origin": "https://dm001-course-hub-ee4hzmlg.edgeone.cool"
  }
];

export function middleware(context) {
  const { request, rewrite, redirect, next } = context;
  const url = new URL(request.url);

  // CourseInfra's own status surface always stays local to the gateway.
  if (url.pathname === '/__infra' || url.pathname.startsWith('/__infra/')) {
    return next();
  }

  for (const route of ROUTES) {
    if (route.mount === '/') {
      const target = new URL(url.pathname + url.search, route.origin + '/');
      return rewrite(target.toString());
    }

    const base = route.mount.slice(0, -1);
    if (url.pathname === base) {
      return redirect(base + '/' + url.search, 308);
    }

    if (url.pathname.startsWith(route.mount)) {
      const rest = url.pathname.slice(base.length) || '/';
      const target = new URL(rest + url.search, route.origin + '/');
      return rewrite(target.toString());
    }
  }

  return next();
}

export const config = { matcher: ['/:path*'] };
