import { mkdir, readFile, writeFile } from 'node:fs/promises';

const registryPath = new URL('../config/apps.json', import.meta.url);
const gatewayDir = new URL('../gateway/', import.meta.url);
const infraDir = new URL('../gateway/__infra/', import.meta.url);
const registry = JSON.parse(await readFile(registryPath, 'utf8'));

const routes = registry.apps
  .filter((app) => app.routeEnabled)
  .sort((a, b) => {
    if (a.mount === '/') return 1;
    if (b.mount === '/') return -1;
    return b.mount.length - a.mount.length;
  })
  .map((app) => ({ id: app.id, mount: app.mount, origin: app.origin.replace(/\/$/, '') }));

const middleware = `// AUTO-GENERATED by scripts/render-gateway.mjs. Do not edit by hand.\nconst ROUTES = ${JSON.stringify(routes, null, 2)};\n\nexport function middleware(context) {\n  const { request, rewrite, redirect, next } = context;\n  const url = new URL(request.url);\n\n  // CourseInfra's own status surface always stays local to the gateway.\n  if (url.pathname === '/__infra' || url.pathname.startsWith('/__infra/')) {\n    return next();\n  }\n\n  for (const route of ROUTES) {\n    if (route.mount === '/') {\n      const target = new URL(url.pathname + url.search, route.origin + '/');\n      return rewrite(target.toString());\n    }\n\n    const base = route.mount.slice(0, -1);\n    if (url.pathname === base) {\n      return redirect(base + '/' + url.search, 308);\n    }\n\n    if (url.pathname.startsWith(route.mount)) {\n      const rest = url.pathname.slice(base.length) || '/';\n      const target = new URL(rest + url.search, route.origin + '/');\n      return rewrite(target.toString());\n    }\n  }\n\n  return next();\n}\n\nexport const config = { matcher: ['/:path*'] };\n`;

const publicStatus = {
  generatedAt: new Date().toISOString(),
  gateway: {
    project: registry.gateway.edgeoneProject,
    domain: registry.gateway.customDomain,
    site: registry.gateway.site
  },
  apps: registry.apps.map((app) => ({
    id: app.id,
    name: app.name,
    repo: app.repo,
    mount: app.mount,
    edgeoneProject: app.edgeoneProject,
    deployEnabled: app.deployEnabled,
    basePathReady: app.basePathReady,
    routeEnabled: app.routeEnabled,
    originConfigured: Boolean(app.origin),
    notes: app.notes ?? ''
  }))
};

await mkdir(gatewayDir, { recursive: true });
await mkdir(infraDir, { recursive: true });
await writeFile(new URL('./middleware.js', gatewayDir), middleware);
await writeFile(new URL('./apps.json', infraDir), JSON.stringify(publicStatus, null, 2) + '\n');

console.log(`Rendered Gateway with ${routes.length} active route(s).`);
